#!/usr/bin/env python3
"""Generate the Literature Review chapter as a formatted MS Word document.
Formatting: Times New Roman 12 pt, 1.5 line spacing, justified body text,
APA 7th edition references with hanging indent.
"""

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING

# ---------------------------------------------------------------- content --

CONTENT = [
    ("h1", "3. Literature Review"),

    ("p", "Nitrogen occupies a central position in global rice production, yet a substantial share of the nitrogen applied to paddy fields is never recovered by the crop within the season of application (Lei et al., 2024). Meta-analyses of isotope-labelled field trials indicate that roughly one-third of applied fertilizer nitrogen accumulates in the soil as residual nitrogen, where it persists across seasons and constitutes what is increasingly termed the legacy nitrogen pool (Lei et al., 2024). The behaviour of this pool has profound implications for fertilizer economics, groundwater quality, and greenhouse gas emissions, because legacy nitrogen may either subsidize subsequent crops or be lost to the wider environment depending on soil, climate, and management conditions (Zhao et al., 2024). Understanding where legacy nitrogen resides in the soil profile, how long it persists, and which processes govern its depletion is therefore a prerequisite for sustainable nutrient management in rice-based systems (Bi et al., 2023)."),

    ("p", "This chapter reviews the recent literature that frames the present study of legacy nitrogen in the paddy-cultivated soils of Gumai Beel, Bangladesh. The review is organized in ten sections: the concept of legacy nutrients; nitrogen dynamics in flooded paddy soils; seasonal and fallow-period nitrogen losses; vertical stratification of soil nutrients; phosphorus dynamics and legacy phosphorus; potassium dynamics; nutrient management in rice-based systems of Bangladesh; spatial variability and geostatistical assessment; statistical approaches used in soil nutrient research; and the research gaps that motivate this thesis (Kamuruzzaman et al., 2024). Throughout, emphasis is placed on studies published between 2020 and 2026, with particular attention to wetland and monsoon-influenced rice systems that most closely resemble the agro-hydrological setting of the present study area (Islam et al., 2023)."),

    ("h2", "3.1 The Concept of Legacy Nutrients in Agricultural Soils"),

    ("p", "Fertilizer nitrogen applied to cropland follows three principal fates: uptake by the current crop, accumulation within the soil profile, and loss to the atmosphere or hydrosphere (Lei et al., 2024). A comprehensive meta-analysis of nitrogen-15 field trials in cereal cropping systems demonstrated that crop recovery in the season of application rarely exceeds half of the applied dose, while approximately one-third of the fertilizer nitrogen is retained in the soil after harvest (Lei et al., 2024). This retained fraction, referred to interchangeably as residual or legacy nitrogen, is not inert; it undergoes continued transformation among mineral, microbial, and organic pools, and its subsequent availability depends strongly on the timing and intensity of mineralization relative to the demand of succeeding crops (Lei et al., 2024). The same synthesis identified application rate, soil organic matter status, and post-harvest water regime as the dominant controls on how much residual nitrogen persists and for how long (Lei et al., 2024)."),

    ("p", "Long-term isotopic evidence from rice-based rotations provides the most direct measurements of legacy nitrogen behaviour currently available (Zhao et al., 2024). In a seventeen-year nitrogen-15 tracing experiment in a rice–wheat system, residual fertilizer nitrogen was found to flow predominantly to subsequent crops rather than to the environment, with cumulative post-season losses amounting to only a few percent of the residual pool (Zhao et al., 2024). Approximately seventy percent of the fertilizer nitrogen remaining in the profile was concentrated within the top twenty centimetres of soil, and the estimated residence time of fertilizer nitrogen in the system was twenty-three to thirty-one years (Zhao et al., 2024). These findings indicate that, under favourable paddy management, legacy nitrogen constitutes a slow-release reserve of considerable agronomic value rather than simply a pollution liability (Zhao et al., 2024)."),

    ("p", "Field-scale nitrogen-15 microplot studies complement these long-term observations by quantifying the size and placement of the residual pool after a single season (Bi et al., 2023). In paddy soils of Northeast China, residual fertilizer nitrogen in the upper forty centimetres ranged from roughly eighteen to thirty-two kilograms of nitrogen per hectare, equivalent to residual rates of nineteen to twenty-five percent of the applied dose (Bi et al., 2023). Critically, the majority of this residue, between fifty-eight and eighty-four percent, was concentrated in the uppermost ten centimetres, and its concentration declined systematically with depth (Bi et al., 2023). Only about five percent of the residual nitrogen was taken up by the following crop, underscoring that the fate of the legacy pool between seasons is governed largely by soil processes rather than by plant demand (Bi et al., 2023)."),

    ("p", "The environmental dimension of legacy nitrogen is equally consequential (Zhao et al., 2024). Where residual nitrogen escapes recapture by subsequent crops, it feeds nitrate enrichment of groundwater and sustained nitrous oxide emissions long after the original application, and accumulated legacy nitrogen is increasingly invoked to explain why water quality responds so slowly to reductions in current fertilizer inputs (Lei et al., 2024). Quantifying the size, placement, and persistence of the residual pool is therefore as much an environmental accounting exercise as an agronomic one, and depth-resolved field measurement provides the empirical basis for both purposes (Bi et al., 2023)."),

    ("p", "Although the legacy concept was developed principally for nitrogen, recent work demonstrates that phosphorus and potassium exhibit analogous but mechanistically distinct legacy behaviour (Yu et al., 2026). Accumulated legacy phosphorus in phosphorus-enriched paddy soils can sustain rice yields across successive seasons without fresh phosphate additions, functioning as a chemically stabilized reserve (Yu et al., 2026). Conversely, long-term potassium budgets show that continuous crop removal without replenishment mines the potassium reserve preferentially from the subsoil, a depletion that conventional topsoil testing systematically underestimates (Correndo et al., 2021). These contrasts imply that legacy nutrient assessment must be nutrient-specific and depth-resolved, a methodological principle adopted in the present study (Correndo et al., 2021)."),

    ("h2", "3.2 Nitrogen Dynamics in Flooded Paddy Soils"),

    ("p", "The defining feature of paddy soils is the alternation between flooded, anaerobic conditions during cultivation and aerobic conditions during drainage and fallow, which produces a redox environment unlike that of any upland soil (Zuo et al., 2022). Under submergence, ammonium is the dominant mineral nitrogen form, while thin oxidized layers at the soil–water interface and around rice roots support nitrification, feeding coupled nitrification–denitrification that converts mineral nitrogen to gaseous forms (Zuo et al., 2022). Experimental manipulation of soil moisture and depth in two contrasting paddy soils showed that nitrous oxide production and the abundances of nitrifying and denitrifying microbial genes decline sharply with soil depth and respond strongly to water regime, confirming that both vertical position and hydrology regulate nitrogen transformation intensity within the profile (Zuo et al., 2022)."),

    ("p", "Nitrogen use efficiency in paddy systems remains persistently low, with roughly half of the applied fertilizer nitrogen lost during the season of application in many field balances (Zhao et al., 2024). In Northeast Chinese paddies, ammonia volatilization, leaching, and surface runoff were individually modest, but apparent denitrification accounted for approximately forty-three percent of applied nitrogen, identifying gaseous loss as the dominant leakage pathway under flooded management (Bi et al., 2023). The practical consequence is that the quantity of nitrogen entering the legacy pool after each season reflects a competition between microbial immobilization and stabilization on one hand and denitrification and hydrological export on the other, with the balance determined by water management and residue inputs (Bi et al., 2023)."),

    ("p", "Management interventions can shift this balance appreciably (Kamuruzzaman et al., 2024). A three-season field evaluation of nitrogen management options in wetland rice on calcareous soil in Bangladesh found that deep placement of urea super granules increased nitrogen use efficiency by thirteen percent, agronomic efficiency by twenty percent, and recovery efficiency by nineteen percent relative to broadcast prilled urea, while permitting an eight percent reduction in the application rate without yield penalty (Kamuruzzaman et al., 2024). Placement strategies of this kind reduce the concentration of mineral nitrogen in the surface floodwater where volatilization and runoff losses originate, thereby retaining more nitrogen within the soil profile where it can contribute to the residual pool (Kamuruzzaman et al., 2024)."),

    ("p", "Fertilizer formulation interacts with placement in determining post-season residual nitrogen (Xiao et al., 2023). Coupling localized (root-zone) nitrogen supply with controlled-release urea in paddy fields significantly increased total nitrogen uptake and the nitrogen residual retained in the soil–crop system, while reducing apparent nitrogen loss by as much as fifty to seventy-five percent relative to conventional practice (Xiao et al., 2023). Such findings demonstrate that the size of the legacy nitrogen pool is not an immutable property of the soil but a management outcome, and they justify the attention paid in the present study to the fertilizer practices operating in the study area (Xiao et al., 2023)."),

    ("p", "Nitrogen fertilization also exerts indirect effects on the soil environment that conditions legacy nutrient behaviour (Begum et al., 2021). In a long-term subtropical wheat–mungbean–rice rotation, elevated nitrogen rates significantly increased particulate organic carbon, microbial biomass carbon, and carbon lability indices, with effects consistently more pronounced in the surface layer than at depth (Begum et al., 2021). Because soil organic matter is the principal matrix in which residual nitrogen is stabilized, such fertilization-driven changes in carbon pools and their stratification directly shape the capacity of each soil layer to retain legacy nitrogen (Begum et al., 2021)."),

    ("p", "Integrated nutrient management similarly influences the post-harvest nitrogen status of paddy soils (Midya et al., 2021). In two-year trials in the Lower Indo-Gangetic Plain, the System of Rice Intensification maintained post-harvest available nitrogen of 326 and 287 kilograms per hectare in consecutive years, significantly exceeding aerobic and conventional transplanted culture, while integrated organic\u2013inorganic treatments raised available nitrogen significantly above sole-fertilizer controls (Midya et al., 2021). Establishment method and nutrient source thus jointly determine the mineral nitrogen stock remaining in the profile at harvest, which constitutes the starting inventory of the legacy pool for the following season (Midya et al., 2021)."),

    ("p", "Seasonal contrasts between the irrigated boro and rainfed aman crops further complicate nitrogen management in double-cropped systems (Salahin et al., 2022). The two seasons differ in water source, temperature regime, and residue context, and multi-season experiments accordingly report that optimal nitrogen rates and the responses of soil properties differ between the boro and aman phases of the rotation (Salahin et al., 2022). Nitrogen budgeting at the whole-rotation scale, rather than for single seasons in isolation, is therefore necessary to capture the carryover of residual nitrogen from one crop to the next (Xiao et al., 2023)."),

    ("h2", "3.3 Seasonal Dynamics and Fallow-Period Nitrogen Losses"),

    ("p", "The transitions between cropping seasons, rather than the cropping periods themselves, are increasingly recognized as the critical windows during which soil nitrogen reserves are depleted (Yaméogo et al., 2021). In lowland rice systems of the West African savanna, soil nitrate accumulated markedly during the dry-to-wet season transition as mineralization proceeded under aerobic conditions, and then largely disappeared upon reflooding through leaching and denitrification (Yaméogo et al., 2021). Vegetation grown during the transition period captured much of this nitrate, reducing its accumulation from over forty kilograms of nitrogen per hectare under bare fallow to as little as one to twenty-three kilograms per hectare, and subsequently increased rice yields when incorporated as green manure (Yaméogo et al., 2021). These observations establish the fallow interval as a period of acute vulnerability for the legacy nitrogen pool in seasonally flooded systems (Yaméogo et al., 2021)."),

    ("p", "Gas flux measurements corroborate the significance of the fallow period in annual nitrogen budgets (Ju et al., 2024). Continuous three-year monitoring of a mono-rice paddy under urea fertilization revealed that nitrous oxide emissions during the fallow period contributed up to approximately ninety percent of whole-year emissions, with the largest flux events triggered by rainfall or irrigation onto dry soil and by transitions between aerobic and anaerobic states (Ju et al., 2024). The mechanistic implication is that mineral nitrogen accumulating in the profile after harvest is progressively converted to gaseous forms during each wetting–drying cycle of the intercrop period, directly depleting the residual pool that would otherwise carry over to the next season (Ju et al., 2024)."),

    ("p", "Management of the cultivation period also modulates how much nitrogen survives to the fallow (Bordoloi et al., 2022). Field experiments in tropical rice paddies demonstrated that jointly optimizing nitrogen rate and tillage practice reduced nitrous oxide emissions while maximizing nitrogen use efficiency and productivity, indicating that emission-efficient management retains proportionally more nitrogen in plant and soil pools (Bordoloi et al., 2022). Since wetting and drying cycles amplify both nitrification and denitrification, the interaction between residual mineral nitrogen and the post-harvest water regime largely determines the fraction of legacy nitrogen lost between seasons (Bordoloi et al., 2022)."),

    ("p", "Taken together, these studies suggest a fundamental climatic contrast in legacy nitrogen behaviour (Zhao et al., 2024). In temperate rice–wheat systems with managed drainage, residual fertilizer nitrogen persists for decades and is progressively recycled to crops (Zhao et al., 2024). In monsoon-influenced tropical systems, by contrast, the pronounced alternation of saturation and desiccation during long fallow intervals exposes the residual pool to repeated episodes of nitrate formation followed by leaching and denitrification, so that legacy nitrogen may be substantially depleted within a single intercrop period (Ju et al., 2024). Establishing which of these regimes better describes wetland paddy systems in Bangladesh is one of the empirical questions addressed by the present study (Ju et al., 2024)."),

    ("p", "Where a full cropping cycle intervenes between successive observations of the soil, the apparent seasonal change in nutrient stocks integrates crop uptake, fresh fertilization, and transition-period losses simultaneously (Yam\u00e9ogo et al., 2021). Monitoring designs in rice systems therefore benefit from sampling immediately after harvests, when the residual pool is most directly interpretable, and from explicit documentation of the cropping calendar so that intervals containing unsampled crops are recognized during interpretation (Wihardjaka et al., 2022). This design principle underlies the sampling schedule adopted in the present study, in which two post-harvest campaigns bracket one complete monsoon rice cycle (Ju et al., 2024)."),

    ("h2", "3.4 Vertical Stratification of Soil Nutrients"),

    ("p", "Depth-wise characterization of soil profiles consistently reveals systematic vertical gradients in macronutrient availability (Mandal & Ghosh, 2021). In profiles from paddy-growing areas of Birbhum district, West Bengal, available nitrogen, phosphorus, potassium, and sulphur all declined with increasing depth, and the macronutrient contents correlated positively with organic carbon and negatively with pH along the profile (Mandal & Ghosh, 2021). Such gradients arise because fertilizer inputs, residue returns, and biological activity are concentrated at the surface, whereas subsoil horizons receive nutrients principally through leaching and root turnover (Mandal & Ghosh, 2021)."),

    ("p", "Long-term fertilization experiments demonstrate that management history reshapes these vertical patterns over decadal timescales (Li et al., 2020). After thirty-four years of treatment in a paddy soil, both chemical fertilizer alone and chemical fertilizer combined with organic manure markedly increased nitrogen forms in the plough layer, with nitrate nitrogen rising by seventy and one hundred eleven percent respectively, while the contents of all nitrogen forms declined progressively along the soil depth gradient to one metre (Li et al., 2020). The combined organic treatment additionally reduced nitrate concentrations in the twenty to forty centimetre layer, thereby lowering the risk of nitrate leaching into deeper strata (Li et al., 2020). These results illustrate that fertilization strategy governs not only the total size of soil nutrient stocks but also their vertical placement, which in turn conditions their vulnerability to loss (Li et al., 2020)."),

    ("p", "In lowland rice systems, tillage exerts a distinctive homogenizing influence on the upper profile (Kalita et al., 2020). Puddling, the wet tillage operation that precedes transplanting, mechanically destroys soil aggregates and churns the upper fifteen to twenty centimetres into structureless mud, while forming a compacted plough pan beneath the puddled zone that restricts percolation (Kalita et al., 2020). This periodic mixing redistributes nutrients within the plough layer at the start of each cropping cycle, temporarily erasing stratification that subsequently redevelops through surface inputs and differential uptake (Kalita et al., 2020). Interpretation of depth-wise nutrient data from paddy fields must therefore account for the timing of sampling relative to tillage events (Kalita et al., 2020)."),

    ("p", "Methodologically, depth-stratified composite sampling has become the standard design for fertility assessment in rice-based systems (Temjen, 2022). Assessments across the rice–wheat belt of the western Terai of Nepal, for example, sampled fixed depth increments after harvest and demonstrated clear fertility differentiation among layers, with the surface horizon identified as the most critical for shallow-rooted cereals (Temjen, 2022). Recent depth-stratified studies further show that post-hoc contrasts between soil layers are frequently threshold-like rather than gradual, with the shallowest and deepest layers differing significantly while adjacent intermediate depths remain statistically indistinguishable (Madnee et al., 2025). These design and interpretation precedents inform both the sampling protocol and the statistical treatment adopted in this thesis (Madnee et al., 2025)."),

    ("p", "Stratification extends beyond the nutrients themselves to the carbon substrates that regulate their cycling (Begum et al., 2021). Stratification ratios of particulate organic carbon, microbial biomass carbon, and permanganate-oxidizable carbon between surface and subsurface layers increased significantly under optimum nitrogen fertilization in rice-based rotations, and such ratios are widely interpreted as sensitive indicators of improving soil quality (Begum et al., 2021). Because microbial activity concentrated near the surface both immobilizes and remineralizes nitrogen, carbon stratification amplifies the contrast between a biologically dynamic topsoil and a comparatively inert subsoil, reinforcing depth as a first-order variable in legacy nutrient assessment (Begum et al., 2021)."),

    ("h2", "3.5 Phosphorus Dynamics and Legacy Phosphorus in Paddy Soils"),

    ("p", "Phosphorus behaviour in paddy soils is dominated by its strong affinity for iron and aluminium oxides, which renders it far less mobile than nitrogen (Biswas et al., 2024). A forty-two-year fertilization experiment in subtropical rice-based cropping systems of Bangladesh showed that labile, residual, and total phosphorus became strongly stratified in the uppermost five centimetres, while specific organic and acid-soluble fractions accumulated at depth, and concluded that long-term fertilization saturates the sorption sites of the surface soil (Biswas et al., 2024). Because fertilizer phosphorus remains close to its point of placement, the vertical distribution of phosphorus is a comparatively stable structural feature of the profile rather than a seasonally dynamic property (Biswas et al., 2024)."),

    ("p", "Within this stratified framework, redox oscillations govern the chemical form and short-term availability of phosphorus (Martinengo et al., 2025). Analysis of twelve flooded paddy soils spanning a wide range of total phosphorus contents found that redox-sensitive inorganic and organic pools together accounted for roughly two-thirds of total phosphorus, and that total phosphorus status determined which organic species dominated and how rapidly they were hydrolysed to support rice nutrition (Martinengo et al., 2025). Reductive dissolution of iron(III) oxides under submergence releases sorbed phosphate to solution, while re-oxidation upon drainage causes iron(III) oxyhydroxides to re-precipitate and re-adsorb phosphate throughout the profile (Martinengo et al., 2025)."),

    ("p", "The temporal signature of these redox processes is a transient pulse of dissolved reactive phosphorus following submergence (Palihakkara et al., 2025). In contrasting tropical paddy soils, dissolved reactive phosphorus peaked within the first one to three weeks after flooding of fertilized soils and declined sharply thereafter as solubilized phosphorus was resorbed onto iron and aluminium phases (Palihakkara et al., 2025). This pulse-and-resorption dynamic helps explain the long-standing observation that rice yield response to phosphorus fertilizer in submerged soils is inconsistent and cannot be predicted from conventional soil tests alone (Palihakkara et al., 2023). For seasonal monitoring studies, it implies that modest fluctuations in extractable phosphorus between sampling campaigns can occur without any change in the underlying depth distribution (Palihakkara et al., 2023)."),

    ("p", "Simulation studies extend these mechanistic insights to management assessment (Liang et al., 2025). Seven-year field data coupled with HYDRUS-1D modelling of rice paddies demonstrated that phosphorus remained concentrated in the upper profile under all fertilization strategies, but that full organic substitution caused excessive topsoil accumulation and elevated leaching risk, whereas partial organic substitution optimized use efficiency with minimal downward transport (Liang et al., 2025). Complementary field comparisons of integrated rice cropping systems found that cropping system and soil layer each significantly affected most phosphorus fractions, whereas their interaction was significant only for the labile pool, confirming the general insensitivity of the phosphorus depth gradient to management and season (Wang et al., 2022)."),

    ("p", "Fractionation studies clarify which phosphorus pools actually respond to management within this stable physical framework (Wang et al., 2022). In integrated rice\u2013fish\u2013duck, rice\u2013vegetable, and conventional rice systems of the Pearl River Delta, moderately labile phosphorus dominated the stock at forty-one to forty-nine percent of total soil phosphorus, and integrated farming significantly increased soil organic carbon, microbial biomass phosphorus, and acid phosphatase activity, which together governed the conversion of stable fractions into plant-available forms (Wang et al., 2022). Organic carbon inputs and phosphatase-mediated mineralization therefore act as biological levers on a pool whose vertical placement is otherwise fixed by sorption chemistry (Wang et al., 2022)."),

    ("p", "The stability of soil phosphorus reserves underpins the emerging concept of legacy phosphorus utilization (Yu et al., 2026). In phosphorus-enriched Taiwanese paddy soils, omission of phosphate fertilizer for two consecutive rice seasons caused no significant reduction in grain yield or grain phosphorus concentration, because moderately labile and slowly labile pools were progressively redistributed into plant-available forms during cultivation (Yu et al., 2026). Legacy phosphorus thus behaves as a long-term buffer that can substitute for fresh inputs over multi-season horizons, in marked contrast to the seasonally volatile legacy nitrogen pool, and this contrast provides a valuable interpretive benchmark for multi-nutrient legacy assessments such as the present study (Yu et al., 2026)."),

    ("h2", "3.6 Potassium Dynamics in Paddy Soil Systems"),

    ("p", "Potassium in paddy soils cycles among solution, exchangeable, non-exchangeable, and mineral lattice forms that exist in dynamic equilibrium (Darunsontaya & Jindaluang, 2021). Incubation of illite-containing rice soils demonstrated that potassium released from decomposing rice straw enters the water-soluble pool within days, with approximately ninety percent of straw-bound potassium liberated almost immediately after incorporation, before slower exchange and fixation reactions redistribute it among soil phases (Darunsontaya & Jindaluang, 2021). Straw and stubble management is consequently among the strongest short-term controls on surface-soil potassium availability in rice systems (Darunsontaya & Jindaluang, 2021)."),

    ("p", "Over longer timescales, continuous rice cultivation modifies the capacity of the soil to supply and retain potassium (Han et al., 2021). A subtropical paddy soil chronosequence showed that prolonged cultivation increased water-soluble and non-exchangeable potassium but decreased exchangeable potassium relative to the original soils, and attributed the declining supply and adsorption capacity to leaching losses of clay and iron oxide sorbents together with competitive occupation of sorption sites by accumulated organic matter (Han et al., 2021). The study concluded that sustained potassium inputs exceeding crop removal are required to maintain the potassium-supplying capacity of long-cultivated paddy soils (Han et al., 2021)."),

    ("p", "The redox regime of paddy fields additionally mobilizes potassium from mineral reserves (Han et al., 2024). In purple paddy soils cultivated for forty years, submergence increased the concentrations of ferrous iron and calcium ions, which substituted for interlayer potassium in illite and thereby released structurally bound potassium into plant-accessible forms, with alternating reduction and oxidation identified as the key driver of this transformation (Han et al., 2024). Redox-driven activation of mineral potassium means that flooded rice systems can draw on reserves that would remain inert in upland soils, partially offsetting negative potassium balances (Han et al., 2024)."),

    ("p", "Profile-scale evidence emphasizes that potassium depletion and enrichment are strongly depth-dependent (Correndo et al., 2021). Long-term budgets in high-potassium agricultural soils revealed that continuous removal without replenishment depleted exchangeable and slowly exchangeable potassium principally in the subsoil between twenty and one hundred centimetres, while topsoil test values remained deceptively stable (Correndo et al., 2021). Conversely, surveys of rice-based cropping systems on Gangetic alluvium found that most potassium fractions reached their maxima in the thirty to forty-five centimetre layer, reflecting clay accumulation and cation exchange capacity at depth, so that inverted or bottom-heavy potassium profiles are a documented feature of alluvial paddy landscapes (Mondal & Kundu, 2025)."),

    ("p", "For wetland rice soils of Bangladesh specifically, the non-exchangeable reserve has been shown to dominate potassium supply under deficit management (Islam et al., 2023). Successive cropping of eighteen Bangladeshi soils without potassium input progressively depleted both exchangeable and non-exchangeable pools, and by the seventh consecutive crop the non-exchangeable fraction contributed eighty-three to ninety-three percent of plant uptake (Islam et al., 2023). Field studies in rainfed lowland rice similarly showed that exchangeable and non-exchangeable potassium peak in mid-season and decline by harvest, and that straw compost effectively substitutes for inorganic potassium fertilizer in replenishing the exchangeable pool (Wihardjaka et al., 2022). Together, these studies establish that potassium sustainability in rice systems hinges on the balance between residue return at the surface and slow reserve depletion at depth (Wihardjaka et al., 2022)."),

    ("p", "Potassium budgeting studies in intensive rice rotations consistently report negative balances wherever straw is removed from the field (Wihardjaka et al., 2022). Because rice accumulates most of its potassium in the straw rather than the grain, the fate of straw at harvest effectively determines whether a season closes with a potassium surplus or deficit, and straw compost application in rainfed lowland rice significantly increased both grain yield and the exchangeable potassium supply relative to inorganic fertilizer alone (Wihardjaka et al., 2022). Under conservation agriculture in Bangladesh, increased residue retention likewise raised soil potassium alongside organic matter and nitrogen, confirming residue return as the pivotal potassium input in these systems (Salahin et al., 2022)."),

    ("h2", "3.7 Nutrient Management in Rice-Based Systems of Bangladesh"),

    ("p", "Rice production in Bangladesh operates under intense pressure to raise yields while curbing fertilizer losses, and national research has therefore concentrated on improving nitrogen use efficiency in wetland culture (Kamuruzzaman et al., 2024). Multi-season trials on calcareous floodplain soil demonstrated that alternative nitrogen management options, including deep-placed urea super granules and biochar-amended prilled urea, significantly improved growth, yield, and all indices of nitrogen use efficiency relative to conventional broadcasting, with deep placement also delivering the most favourable benefit–cost ratio (Kamuruzzaman et al., 2024). Such results indicate substantial headroom for improving the retention of applied nitrogen in Bangladeshi paddy soils through placement and formulation alone (Kamuruzzaman et al., 2024)."),

    ("p", "Cropping system experiments under conservation agriculture provide further evidence that management reshapes soil nutrient status in Bangladeshi rice rotations (Salahin et al., 2022). Across three years of a mustard–boro–aman rotation, strip tillage combined with increased residue retention produced higher soil organic matter, total nitrogen, phosphorus, potassium, and boron than conventional tillage, while nitrogen rates of one hundred to one hundred twenty-five percent of the recommended dose maximized system yield and profitability (Salahin et al., 2022). The authors recommended slightly elevated nitrogen rates during the initial years of conservation practice, followed by reductions as soil fertility accrues, illustrating the dynamic interplay between residue management and fertilizer requirement (Salahin et al., 2022)."),

    ("p", "Long-term nutrient omission and rate trials in the same agro-ecological region reinforce the risks of unbalanced fertilization (Begum et al., 2021). Optimum to moderately elevated nitrogen rates improved soil carbon pools and their stratification in a wheat–mungbean–rice system, whereas suboptimal rates degraded labile carbon fractions that underpin nutrient cycling (Begum et al., 2021). In parallel, potassium supply studies across Bangladeshi wetland soils warn that omission of potassium triggers rapid mining of non-exchangeable reserves, a process invisible to routine soil tests until supply capacity is substantially eroded (Islam et al., 2023). The literature therefore portrays Bangladeshi paddy soils as productive but vulnerable systems in which legacy nutrient reserves are actively drawn down wherever inputs fail to match removals (Islam et al., 2023)."),

    ("p", "National fertilizer guidance in Bangladesh is anchored in soil-test-based recommendations that adjust doses to measured nutrient status, yet adoption at field level remains uneven and applied rates frequently diverge from recommendations in both directions (Kamuruzzaman et al., 2024). Studies of potassium supply across contrasting Bangladeshi soils explicitly caution that recommendations derived from exchangeable potassium alone misjudge the sustainable supply, because the non-exchangeable reserve contributes the dominant share of uptake under deficit fertilization (Islam et al., 2023). These findings argue for periodic re-assessment of soil nutrient status at the local scale, of the kind undertaken in the present study, so that recommendations remain aligned with the evolving legacy nutrient stock (Islam et al., 2023)."),

    ("h2", "3.8 Spatial Variability and Geostatistical Assessment of Soil Nutrients"),

    ("p", "Soil nutrient concentrations vary substantially within single fields and landscapes, and quantifying this spatial structure is essential both for unbiased sampling and for site-specific management (Gangopadhyay & Reddy, 2022). Geostatistical analysis of eighty-eight surface samples under a rice–fallow system in eastern India found that available nitrogen, phosphorus, and potassium each followed distinct semivariogram models, and attributed the observed spatial variability to parent material, soil management, and land use history (Gangopadhyay & Reddy, 2022). Interpolated surfaces derived from such analyses delineate management zones within which fertilizer prescriptions can be differentiated, improving both agronomic efficiency and environmental protection (Gangopadhyay & Reddy, 2022)."),

    ("p", "Grid-based studies at the field scale confirm that spatial dependence in paddy soils is strong enough to justify interpolation-based mapping (Varalakshmi et al., 2023). In a continuously cultivated paddy block sampled on a twenty-metre grid, available nitrogen and potassium exhibited strong spatial dependence while pH, organic carbon, and available phosphorus were moderately dependent, and ordinary kriging with fitted spherical, exponential, and Gaussian models produced reliable surface maps of each property (Varalakshmi et al., 2023). The coefficient of variation among samples reached thirty-four percent for some properties, demonstrating that field means conceal considerable internal heterogeneity (Varalakshmi et al., 2023)."),

    ("p", "For studies of legacy nutrients, spatially explicit mapping serves a diagnostic as well as a management function (Varalakshmi et al., 2023). Persistent hotspots in repeated maps indicate localized controls such as micro-topography, water convergence, or historical fertilization, whereas the synchronous disappearance of hotspots across a field signals a field-wide depletion process rather than sampling noise (Gangopadhyay & Reddy, 2022). Interpolation of georeferenced point observations, whether by kriging or inverse distance weighting, thus complements profile statistics by revealing where within the landscape legacy nutrient reserves persist or collapse between seasons (Gangopadhyay & Reddy, 2022)."),

    ("p", "Both kriging and inverse distance weighting are used to convert point observations into continuous nutrient surfaces, and the choice between them depends on sample density and the strength of spatial autocorrelation (Varalakshmi et al., 2023). Kriging exploits fitted semivariogram models and yields prediction variances, but requires sample sizes large enough to estimate the spatial structure reliably, whereas inverse distance weighting is robust at moderate sample densities and preserves local extremes that kriging tends to smooth (Gangopadhyay & Reddy, 2022). For depth- and season-replicated designs built on a fixed network of sampling points, distance-weighted interpolation offers a transparent and reproducible basis for comparing spatial patterns across successive sampling campaigns (Varalakshmi et al., 2023)."),

    ("h2", "3.9 Statistical Approaches in Soil Nutrient Research"),

    ("p", "Factorial analysis of variance has become the standard inferential framework for evaluating soil nutrient responses to depth and temporal factors simultaneously (Rusu et al., 2025). Recent assessments of orchard and cropland soils employed two-way analysis of variance with interaction terms to test the effects of year, management system, and depth on soil organic carbon, nitrogen, phosphorus, and potassium, verifying normality and homogeneity of variances before testing and applying Tukey's honestly significant difference test for pairwise separation (Rusu et al., 2025). This design detects not only whether each factor matters but whether the depth pattern itself changes over time, which is precisely the signature that distinguishes a dynamic nutrient pool from a structurally stable one (Rusu et al., 2025)."),

    ("p", "Tukey's honestly significant difference test is likewise the dominant post-hoc procedure in rice-system agronomy, and published applications illustrate the interpretive conventions adopted in this thesis (Midya et al., 2021). In integrated nutrient management trials in the Lower Indo-Gangetic Plain, treatments were routinely described as significantly different from most alternatives yet statistically at par with specific others, reflecting the mixture of significant and non-significant pairwise contrasts that mean separation typically yields (Midya et al., 2021). Conservation agriculture trials in Bangladesh similarly reported yields and soil properties at par between adjacent nitrogen rates but significantly different from more distant ones, demonstrating threshold-like rather than continuous treatment separations (Salahin et al., 2022)."),

    ("p", "Finally, the literature cautions that interaction significance is response-variable-specific and must be tested rather than assumed (Zuo et al., 2022). Within a single paddy profile experiment, the interaction of soil layer and water regime was highly significant for nitrous oxide emission yet non-significant for several microbial gene abundances measured on the same samples (Zuo et al., 2022). Comparable analyses of phosphorus fractions found significant layer and system main effects but interactions confined to a single labile pool (Wang et al., 2022). Reporting effect sizes alongside significance, for example as the proportion of total variance explained by each source, is increasingly recommended so that statistically significant but practically minor effects are not over-interpreted (Rusu et al., 2025)."),

    ("h2", "3.10 Research Gaps and Synthesis"),

    ("p", "Three gaps emerge from the reviewed literature. First, the most rigorous quantifications of legacy nitrogen derive from long-term isotopic experiments in temperate and subtropical rice–wheat rotations, where residual nitrogen proves remarkably persistent (Zhao et al., 2024). Whether comparable persistence occurs in tropical monsoon wetlands, where fallow-period wetting and drying drive intense gaseous and hydrological losses, remains poorly quantified, because few studies have tracked the residual pool across complete cropping cycles in such environments (Ju et al., 2024). Single-season residual measurements exist for temperate paddies, but multi-season, depth-resolved observations from seasonally inundated tropical systems are scarce (Bi et al., 2023)."),

    ("p", "Second, legacy nutrient research has treated nitrogen, phosphorus, and potassium largely in isolation, despite mounting evidence that the three nutrients follow fundamentally different persistence regimes: seasonally volatile for nitrogen, chemically buffered for phosphorus, and depth-partitioned with slow subsoil mining for potassium (Yu et al., 2026). Direct multi-nutrient comparisons within a single field, sampling design, and statistical framework are rare, yet they are precisely what is needed to demonstrate that legacy behaviour is nutrient-specific rather than site-specific (Correndo et al., 2021). Wetland rice soils of Bangladesh, where potassium supply already depends heavily on non-exchangeable reserves, are a particularly consequential setting for such comparisons (Islam et al., 2023)."),

    ("p", "Third, spatially explicit assessment of legacy nutrients remains underdeveloped, with most seasonal monitoring studies reporting only field-mean concentrations that conceal within-field heterogeneity (Varalakshmi et al., 2023). Combining depth-stratified seasonal sampling with georeferenced interpolation would reveal whether legacy nutrient depletion proceeds uniformly or through the collapse of discrete hotspots, information that directly informs site-specific fertilizer management (Gangopadhyay & Reddy, 2022). The present study addresses these three gaps jointly by monitoring nitrogen, phosphorus, and potassium across three depth layers and three seasonal phases of the boro–aman cultivation cycle in Gumai Beel, and by coupling factorial analysis of variance and post-hoc testing with inverse distance weighted mapping of the nitrogen pool (Kamuruzzaman et al., 2024). In doing so, it provides one of the first depth-resolved, multi-season, spatially explicit accounts of legacy nutrient dynamics in a seasonally inundated wetland paddy system of Bangladesh (Islam et al., 2023)."),

    ("h1", "References"),

    ("ref", "Begum, R., Jahangir, M. M. R., Jahiruddin, M., Islam, M. R., Rahman, M. T., & Rahman, M. L. (2021). Nitrogen fertilization impact on soil carbon pools and their stratification and lability in subtropical wheat-mungbean-rice agroecosystems. PLOS ONE, 16(10), e0256397. https://doi.org/10.1371/journal.pone.0256397"),
    ("ref", "Bi, S., Luo, X., Zhang, C., Li, P., Yu, C., Liu, Z., & Peng, X. (2023). Fate of fertilizer nitrogen and residual nitrogen in paddy soil in Northeast China. Journal of Integrative Agriculture, 22(11), 3535\u20133548. https://doi.org/10.1016/j.jia.2023.06.010"),
    ("ref", "Biswas, C., Ferdous, J., Sarker, R. R., Islam, K. R., & Jahangir, M. M. R. (2024). Forty-two years impact of chemical fertilization on soil phosphorus partition and distribution under rice-based cropping systems. PLOS ONE, 19(6), e0305097. https://doi.org/10.1371/journal.pone.0305097"),
    ("ref", "Bordoloi, N., Baruah, K. K., & Maji, T. K. (2022). Identification of optimal level of nitrogen fertilizer and tillage practice to reduce nitrous oxide emissions and maximize the nitrogen use efficiency and productivity from tropical rice paddy. Paddy and Water Environment. https://doi.org/10.1007/s10333-022-00906-6"),
    ("ref", "Correndo, A. A., Rubio, G., Garc\u00eda, F. O., & Ciampitti, I. A. (2021). Subsoil-potassium depletion accounts for the nutrient budget in high-potassium agricultural soils. Scientific Reports, 11, 11597. https://doi.org/10.1038/s41598-021-90297-1"),
    ("ref", "Darunsontaya, T., & Jindaluang, W. (2021). Effect of rice straw on potassium availability in illite containing soils of Central Plain, Thailand. Walailak Journal of Science and Technology, 18(15), 9254. https://doi.org/10.48048/wjst.2021.9254"),
    ("ref", "Gangopadhyay, S. K., & Reddy, G. P. O. (2022). Spatial variability of soil nutrients under the rice-fallow system of eastern India using geostatistics and Geographic Information System. Journal of Soil and Water Conservation, 21(1), 47\u201356. https://doi.org/10.5958/2455-7145.2022.00007.8"),
    ("ref", "Han, G.-Z., Cao, X.-M., Han, B.-S., Yang, F., Huang, L.-M., & Wu, Y.-J. (2021). Potassium supply and adsorption capacity changes in a Chinese subtropical paddy soil chronosequence. Archives of Agronomy and Soil Science, 69(2), 290\u2013303. https://doi.org/10.1080/03650340.2021.1985109"),
    ("ref", "Han, G.-Z., Fan, H., Han, B.-S., Huang, L.-M., Cao, X.-M., & Yang, F. (2024). Paddy management controls potassium release from minerals in purple soils after 40 years of cultivation. European Journal of Soil Science, 75(2), e13492. https://doi.org/10.1111/ejss.13492"),
    ("ref", "Islam, S., Gathala, M. K., Timsina, J., Dutta, S., Salim, M., & Majumdar, K. (2023). Potassium supplying capacity and contribution of non-exchangeable potassium in wetland rice soils in Bangladesh. Communications in Soil Science and Plant Analysis, 54(20), 2745\u20132762. https://doi.org/10.1080/00103624.2023.2240853"),
    ("ref", "Ju, O., Kang, N., Soh, H., Park, J.-S., Choi, E., & Jeong, H. (2024). Nitrous oxide emissions during cultivation and fallow periods from rice paddy soil under urea fertilization. Atmosphere, 15(2), 143. https://doi.org/10.3390/atmos15020143"),
    ("ref", "Kalita, J., Ahmed, P., & Baruah, N. (2020). Puddling and its effect on soil physical properties and growth of rice and post rice crops: A review. Journal of Pharmacognosy and Phytochemistry, 9(4), 503\u2013510."),
    ("ref", "Kamuruzzaman, M., Rees, R. M., Islam, M. T., Drewer, J., Sutton, M. A., Bhatia, A., Bealey, W. J., & Hasan, M. M. (2024). Improving nitrogen fertilizer management for yield and N use efficiency in wetland rice cultivation in Bangladesh. Agronomy, 14(12), 2758. https://doi.org/10.3390/agronomy14122758"),
    ("ref", "Lei, S., Zhao, M., Zhu, H., Xia, M., Chen, Z., & Zhou, J. (2024). Fates and controlling factors of nitrogen fertilizers in relation to grain yield after the application season in wheat cropping systems: A meta-analysis of 15N field trials. Field Crops Research, 310, 109364. https://doi.org/10.1016/j.fcr.2024.109364"),
    ("ref", "Li, X., Li, B., Wang, C., Chen, Y., & Ma, P. (2020). Effects of long-term fertilization on different nitrogen forms in paddy along soil depth gradient. American Journal of Plant Sciences, 11(12), 2031\u20132042. https://doi.org/10.4236/ajps.2020.1112143"),
    ("ref", "Liang, S., Chu, Q., Ashrafi, A., Zhao, Z., Liu, X., Liu, S., Yang, B., Li, D., He, P., Cao, L., Sha, Z., & Chen, C. (2025). Agricultural practices influence phosphorus transport and ecosystem health in rice-paddy systems: Insights from HYDRUS-1D simulations. Agriculture, Ecosystems & Environment, 385, 109581. https://doi.org/10.1016/j.agee.2025.109581"),
    ("ref", "Madnee, M., Hussain, T., Allahverdi, T. H., Nurrochmat, N. A., Bashir, M. A., Ali, M. M., Ghaffar, M. U., & Qanitha, M. (2025). Enhancing soil fertility in arid and semi-arid climates using leguminous trees: A species-specific agroforestry approach. Journal of Agroforestry and Environment, 18(2), 152\u2013168. https://doi.org/10.55706/jae1834"),
    ("ref", "Mandal, S., & Ghosh, G. K. (2021). Depth-wise distribution of macronutrients (N, P, K, S) and their correlation with soil properties in selected soil profiles of Birbhum district of West Bengal, India. International Journal of Chemical Studies, 9(1), 2801\u20132809. https://doi.org/10.22271/chemi.2021.v9.i1am.11651"),
    ("ref", "Martinengo, S., Chil\u00e0, L., Mazzon, M., Cade-Menun, B., Bordignon, S., Gobetto, R., Martin, M., Santoro, V., & Celi, L. (2025). Soil total phosphorus content is a driver of P forms in continuously flooded paddy soils. Geoderma, 462, 117526. https://doi.org/10.1016/j.geoderma.2025.117526"),
    ("ref", "Midya, A., Saren, B. K., Dey, J. K., Maitra, S., Praharaj, S., Gaikwad, D. J., Gaber, A., Alsanie, W. F., & Hossain, A. (2021). Crop establishment methods and integrated nutrient management improve: Part II. Nutrient uptake and use efficiency and soil health in rice (Oryza sativa L.) field in the Lower Indo-Gangetic Plain, India. Agronomy, 11(9), 1894. https://doi.org/10.3390/agronomy11091894"),
    ("ref", "Mondal, H., & Kundu, M. C. (2025). Vertical distribution of forms of potassium in rice-based cropping systems of Gangetic alluvial soil of West Bengal, India. International Journal of Bio-resource and Stress Management, 16(12). https://doi.org/10.23910/1.2025.6511"),
    ("ref", "Palihakkara, J., Burkitt, L. L., Jeyakumar, P., & Attanayake, C. P. (2023). Exploring phosphorus dynamics in submerged soils and its implications on the inconsistent rice yield response to added inorganic phosphorus fertilisers in paddy soils in Sri Lanka. Journal of Soil Science and Plant Nutrition. https://doi.org/10.1007/s42729-023-01553-4"),
    ("ref", "Palihakkara, J., Attanayake, C. P., Burkitt, L. L., & Jeyakumar, P. (2025). Phosphorus release and transformations in contrasting tropical paddy soils under fertiliser application. Journal of Soil Science and Plant Nutrition. https://doi.org/10.1007/s42729-025-02416-w"),
    ("ref", "Rusu, M., Filip, M., Cara, I. G., \u021aopa, D., & Jit\u0103reanu, G. (2025). Soil nutrient dynamics and farming sustainability under different plum orchard management practices in the pedoclimatical conditions of Moldavian Plateau. Agriculture, 15(5), 509. https://doi.org/10.3390/agriculture15050509"),
    ("ref", "Salahin, N., Alam, M. K., Shil, N. C., Mondol, A. T. M. A. I., Alam, M. J., Kobeasy, M. I., Gaber, A., & Ahmed, S. (2022). Interactive effects of tillage systems and nitrogen fertilizer rates on the performance of mustard-boro-aman rice cropping systems under conservation agriculture practices. Agronomy, 12(7), 1671. https://doi.org/10.3390/agronomy12071671"),
    ("ref", "Temjen, W. (2022). Fertility assessment in different depth of soil in rice-wheat cropping system of Western Terai of Nepal. International Journal for Research in Applied Science and Engineering Technology, 10(3). https://doi.org/10.22214/ijraset.2022.40669"),
    ("ref", "Varalakshmi, P., Sharma, S. H. K., Sreenivas, K., Neelima, T. L., & Supriya, Y. (2023). Quantitative evaluation of the spatial variation of surface soil properties in continuous paddy growing fields. International Journal of Plant & Soil Science, 35(19), 555\u2013566. https://doi.org/10.9734/ijpss/2023/v35i193555"),
    ("ref", "Wang, C., Yang, Q., Zhang, C., Li, X., Chen, J., Zhang, X., Chen, J., & Liu, K. (2022). Rice-fish-duck system regulation of soil phosphorus fraction conversion and availability through organic carbon and phosphatase activity. Frontiers in Environmental Science, 10, 979234. https://doi.org/10.3389/fenvs.2022.979234"),
    ("ref", "Wihardjaka, A., Harsanti, E. S., & Ardiwinata, A. N. (2022). Effect of fertilizer management on potassium dynamics and yield of rainfed lowland rice in Indonesia. Chilean Journal of Agricultural Research, 82(1), 33\u201343. https://doi.org/10.4067/S0718-58392022000100033"),
    ("ref", "Xiao, D., Ding, Z., Cao, Y., Hou, J., Hu, R., & Wang, X. (2023). Effects of local nitrogen supply and nitrogen fertilizer variety coupling on rice nitrogen transport and soil nitrogen balance in paddy fields. Frontiers in Sustainable Food Systems, 7, 1252324. https://doi.org/10.3389/fsufs.2023.1252324"),
    ("ref", "Yam\u00e9ogo, P. L., Becker, M., & Segda, Z. (2021). Seasonal soil nitrogen dynamics affect yields of lowland rice in the savanna zone of West Africa. Journal of Plant Nutrition and Soil Science, 184(1), 98\u2013111. https://doi.org/10.1002/jpln.202000275"),
    ("ref", "Yu, C., Kao, P.-T., & Wang, S.-L. (2026). The availability of legacy phosphorus for rice growth in phosphorus-rich paddy soils: A two-season case study. Agronomy, 16(4), 456. https://doi.org/10.3390/agronomy16040456"),
    ("ref", "Zhao, X., Wang, Y., Cai, S., Ladha, J. K., Castellano, M. J., & Xia, L. (2024). Legacy nitrogen fertilizer in a rice-wheat cropping system flows to crops more than the environment. Science Bulletin, 69(9), 1212\u20131216. https://doi.org/10.1016/j.scib.2024.02.027"),
    ("ref", "Zuo, J., Hu, H., Fu, Q., Zhu, J., Zheng, H., Mo, M., & Tu, A. (2022). Responses of N2O production and abundances of associated microorganisms to soil profiles and water regime in two paddy soils. Agronomy, 12(3), 743. https://doi.org/10.3390/agronomy12030743"),
]

# ------------------------------------------------------------- build docx --

doc = Document()

# Page setup: A4-ish default with 1-inch margins
for section in doc.sections:
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

# Base style
style = doc.styles["Normal"]
style.font.name = "Times New Roman"
style.font.size = Pt(12)


def add_h1(text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(14)
    run.font.name = "Times New Roman"
    p.paragraph_format.space_before = Pt(12)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE


def add_h2(text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(12)
    run.font.name = "Times New Roman"
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE


def add_body(text):
    p = doc.add_paragraph(text)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    pf = p.paragraph_format
    pf.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
    pf.space_after = Pt(6)
    pf.first_line_indent = Inches(0.3)


def add_ref(text):
    p = doc.add_paragraph(text)
    pf = p.paragraph_format
    pf.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
    pf.space_after = Pt(4)
    pf.left_indent = Inches(0.5)
    pf.first_line_indent = Inches(-0.5)  # hanging indent


for kind, text in CONTENT:
    if kind == "h1":
        add_h1(text)
    elif kind == "h2":
        add_h2(text)
    elif kind == "p":
        add_body(text)
    elif kind == "ref":
        add_ref(text)

out = "/workspace/thesis/Literature_Review.docx"
doc.save(out)

body_words = sum(len(t.split()) for k, t in CONTENT if k == "p")
ref_words = sum(len(t.split()) for k, t in CONTENT if k == "ref")
n_paras = sum(1 for k, _ in CONTENT if k == "p")
print(f"Saved {out}")
print(f"Body paragraphs: {n_paras}; body words: {body_words}; reference words: {ref_words}; total: {body_words + ref_words}")
